
#ifndef _C5_de223_
#define _C5_de223_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_BOOLEAN F438_2850(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F438_2851(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void EIF_Minit223(void);
extern EIF_BOOLEAN F93_1302(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F733_5609(EIF_REFERENCE);
extern EIF_REFERENCE F93_1303(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F733_5610(EIF_REFERENCE);
extern EIF_REFERENCE F749_6250(EIF_REFERENCE, EIF_REFERENCE);
extern char *(*R2524[])();

#ifdef __cplusplus
}
#endif

#endif
