/*
 * Code for class HTTP_STATUS_CODE
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F137_1943(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1944(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1945(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1946(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1947(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1948(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1949(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1950(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1951(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1952(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1953(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1954(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1955(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1956(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1957(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1958(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1959(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1960(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1961(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1962(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1963(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1964(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1965(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1966(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1967(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1968(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1969(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1970(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1971(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1972(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1973(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1974(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1975(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1976(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1977(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1978(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1979(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1980(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1981(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1982(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1983(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1984(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1985(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1986(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1987(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1988(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1989(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1990(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1991(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1992(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1993(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1994(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1995(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1996(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1997(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1998(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_1999(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_2000(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_2001(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_2002(EIF_REFERENCE);
extern EIF_TYPED_VALUE F137_2003(EIF_REFERENCE);
extern void EIF_Minit137(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {HTTP_STATUS_CODE}.continue */
EIF_TYPED_VALUE F137_1943 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 100L);
	return r;
}

/* {HTTP_STATUS_CODE}.switching_protocols */
EIF_TYPED_VALUE F137_1944 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 101L);
	return r;
}

/* {HTTP_STATUS_CODE}.processing */
EIF_TYPED_VALUE F137_1945 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 102L);
	return r;
}

/* {HTTP_STATUS_CODE}.ie7_request_uri_too_long */
EIF_TYPED_VALUE F137_1946 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 122L);
	return r;
}

/* {HTTP_STATUS_CODE}.ok */
EIF_TYPED_VALUE F137_1947 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 200L);
	return r;
}

/* {HTTP_STATUS_CODE}.created */
EIF_TYPED_VALUE F137_1948 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 201L);
	return r;
}

/* {HTTP_STATUS_CODE}.accepted */
EIF_TYPED_VALUE F137_1949 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 202L);
	return r;
}

/* {HTTP_STATUS_CODE}.nonauthoritative_info */
EIF_TYPED_VALUE F137_1950 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 203L);
	return r;
}

/* {HTTP_STATUS_CODE}.no_content */
EIF_TYPED_VALUE F137_1951 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 204L);
	return r;
}

/* {HTTP_STATUS_CODE}.reset_content */
EIF_TYPED_VALUE F137_1952 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 205L);
	return r;
}

/* {HTTP_STATUS_CODE}.partial_content */
EIF_TYPED_VALUE F137_1953 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 206L);
	return r;
}

/* {HTTP_STATUS_CODE}.multistatus */
EIF_TYPED_VALUE F137_1954 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 207L);
	return r;
}

/* {HTTP_STATUS_CODE}.im_used */
EIF_TYPED_VALUE F137_1955 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 226L);
	return r;
}

/* {HTTP_STATUS_CODE}.multiple_choices */
EIF_TYPED_VALUE F137_1956 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 300L);
	return r;
}

/* {HTTP_STATUS_CODE}.moved_permanently */
EIF_TYPED_VALUE F137_1957 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 301L);
	return r;
}

/* {HTTP_STATUS_CODE}.found */
EIF_TYPED_VALUE F137_1958 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 302L);
	return r;
}

/* {HTTP_STATUS_CODE}.see_other */
EIF_TYPED_VALUE F137_1959 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 303L);
	return r;
}

/* {HTTP_STATUS_CODE}.not_modified */
EIF_TYPED_VALUE F137_1960 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 304L);
	return r;
}

/* {HTTP_STATUS_CODE}.use_proxy */
EIF_TYPED_VALUE F137_1961 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 305L);
	return r;
}

/* {HTTP_STATUS_CODE}.switch_proxy */
EIF_TYPED_VALUE F137_1962 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 306L);
	return r;
}

/* {HTTP_STATUS_CODE}.temp_redirect */
EIF_TYPED_VALUE F137_1963 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 307L);
	return r;
}

/* {HTTP_STATUS_CODE}.bad_request */
EIF_TYPED_VALUE F137_1964 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 400L);
	return r;
}

/* {HTTP_STATUS_CODE}.unauthorized */
EIF_TYPED_VALUE F137_1965 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 401L);
	return r;
}

/* {HTTP_STATUS_CODE}.payment_required */
EIF_TYPED_VALUE F137_1966 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 402L);
	return r;
}

/* {HTTP_STATUS_CODE}.forbidden */
EIF_TYPED_VALUE F137_1967 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 403L);
	return r;
}

/* {HTTP_STATUS_CODE}.not_found */
EIF_TYPED_VALUE F137_1968 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 404L);
	return r;
}

/* {HTTP_STATUS_CODE}.method_not_allowed */
EIF_TYPED_VALUE F137_1969 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 405L);
	return r;
}

/* {HTTP_STATUS_CODE}.not_acceptable */
EIF_TYPED_VALUE F137_1970 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 406L);
	return r;
}

/* {HTTP_STATUS_CODE}.proxy_auth_required */
EIF_TYPED_VALUE F137_1971 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 407L);
	return r;
}

/* {HTTP_STATUS_CODE}.request_timeout */
EIF_TYPED_VALUE F137_1972 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 408L);
	return r;
}

/* {HTTP_STATUS_CODE}.conflict */
EIF_TYPED_VALUE F137_1973 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 409L);
	return r;
}

/* {HTTP_STATUS_CODE}.gone */
EIF_TYPED_VALUE F137_1974 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 410L);
	return r;
}

/* {HTTP_STATUS_CODE}.length_required */
EIF_TYPED_VALUE F137_1975 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 411L);
	return r;
}

/* {HTTP_STATUS_CODE}.precondition_failed */
EIF_TYPED_VALUE F137_1976 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 412L);
	return r;
}

/* {HTTP_STATUS_CODE}.request_entity_too_large */
EIF_TYPED_VALUE F137_1977 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 413L);
	return r;
}

/* {HTTP_STATUS_CODE}.request_uri_too_long */
EIF_TYPED_VALUE F137_1978 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 414L);
	return r;
}

/* {HTTP_STATUS_CODE}.unsupported_media_type */
EIF_TYPED_VALUE F137_1979 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 415L);
	return r;
}

/* {HTTP_STATUS_CODE}.request_range_not_satisfiable */
EIF_TYPED_VALUE F137_1980 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 416L);
	return r;
}

/* {HTTP_STATUS_CODE}.expectation_failed */
EIF_TYPED_VALUE F137_1981 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 417L);
	return r;
}

/* {HTTP_STATUS_CODE}.teapot */
EIF_TYPED_VALUE F137_1982 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 418L);
	return r;
}

/* {HTTP_STATUS_CODE}.too_many_connections */
EIF_TYPED_VALUE F137_1983 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 421L);
	return r;
}

/* {HTTP_STATUS_CODE}.unprocessable_entity */
EIF_TYPED_VALUE F137_1984 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 422L);
	return r;
}

/* {HTTP_STATUS_CODE}.locked */
EIF_TYPED_VALUE F137_1985 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 423L);
	return r;
}

/* {HTTP_STATUS_CODE}.failed_dependency */
EIF_TYPED_VALUE F137_1986 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 424L);
	return r;
}

/* {HTTP_STATUS_CODE}.unordered_collection */
EIF_TYPED_VALUE F137_1987 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 425L);
	return r;
}

/* {HTTP_STATUS_CODE}.upgrade_required */
EIF_TYPED_VALUE F137_1988 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 426L);
	return r;
}

/* {HTTP_STATUS_CODE}.no_response */
EIF_TYPED_VALUE F137_1989 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 444L);
	return r;
}

/* {HTTP_STATUS_CODE}.retry_with */
EIF_TYPED_VALUE F137_1990 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 449L);
	return r;
}

/* {HTTP_STATUS_CODE}.blocked_parental */
EIF_TYPED_VALUE F137_1991 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 450L);
	return r;
}

/* {HTTP_STATUS_CODE}.client_closed_request */
EIF_TYPED_VALUE F137_1992 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 499L);
	return r;
}

/* {HTTP_STATUS_CODE}.internal_server_error */
EIF_TYPED_VALUE F137_1993 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 500L);
	return r;
}

/* {HTTP_STATUS_CODE}.not_implemented */
EIF_TYPED_VALUE F137_1994 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 501L);
	return r;
}

/* {HTTP_STATUS_CODE}.bad_gateway */
EIF_TYPED_VALUE F137_1995 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 502L);
	return r;
}

/* {HTTP_STATUS_CODE}.service_unavailable */
EIF_TYPED_VALUE F137_1996 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 503L);
	return r;
}

/* {HTTP_STATUS_CODE}.gateway_timeout */
EIF_TYPED_VALUE F137_1997 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 504L);
	return r;
}

/* {HTTP_STATUS_CODE}.http_version_not_supported */
EIF_TYPED_VALUE F137_1998 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 505L);
	return r;
}

/* {HTTP_STATUS_CODE}.variant_also_negotiates */
EIF_TYPED_VALUE F137_1999 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 506L);
	return r;
}

/* {HTTP_STATUS_CODE}.insufficient_storage */
EIF_TYPED_VALUE F137_2000 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 507L);
	return r;
}

/* {HTTP_STATUS_CODE}.bandwidth_limit_exceeded */
EIF_TYPED_VALUE F137_2001 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 509L);
	return r;
}

/* {HTTP_STATUS_CODE}.not_extended */
EIF_TYPED_VALUE F137_2002 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 510L);
	return r;
}

/* {HTTP_STATUS_CODE}.user_access_denied */
EIF_TYPED_VALUE F137_2003 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 530L);
	return r;
}

void EIF_Minit137 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
