
#ifndef _C9_fu430_
#define _C9_fu430_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_BOOLEAN F731_5543(EIF_REFERENCE);
extern EIF_BOOLEAN F731_5545(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F731_5547(EIF_REFERENCE, EIF_REFERENCE);
extern void F731_5548(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F731_5552(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER, EIF_POINTER, EIF_INTEGER_32, EIF_BOOLEAN, EIF_INTEGER_32, EIF_INTEGER_32, EIF_INTEGER_32, EIF_POINTER);
extern void EIF_Minit430(void);
extern EIF_BOOLEAN F728_5509(EIF_REFERENCE, EIF_REFERENCE);
extern void F728_5516(EIF_REFERENCE, EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
