/*
 * Generated by ISE 14.05.9.5417 GPL Edition - macosx-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F311_5702();
extern void F315_5965();
extern void F309_5629();
extern void F314_5874();
extern void F430_4794();
extern void F428_5509();
extern void F82_1351();
extern EIF_REFERENCE F82_1338();
extern EIF_BOOLEAN F82_1350();
extern EIF_BOOLEAN F82_1355();
extern void F82_1360();
extern void F82_1361();
extern void F82_1362();
extern void F123_1760();
extern EIF_TYPED_VALUE F123_1761();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F311_5702;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F309_5629;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F430_4794;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F315_5965;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F314_5874;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F428_5509;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F82_1351;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F82_1350;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F82_1338;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F82_1355;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F82_1360;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F82_1361;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F82_1362;

	egc_str_dtype = 314;

	egc_str32_dtype = 313;
	egc_arr_dtype = 429;
	egc_tup_dtype = 293;
	egc_disp_rout_id = 2998;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)627;
	egc_sp_wchar = (EIF_TYPE_INDEX)811;
	egc_sp_bool = (EIF_TYPE_INDEX)693;
	egc_sp_uint8 = (EIF_TYPE_INDEX)766;
	egc_sp_uint16 = (EIF_TYPE_INDEX)885;
	egc_sp_uint32 = (EIF_TYPE_INDEX)486;
	egc_sp_uint64 = (EIF_TYPE_INDEX)538;
	egc_sp_int8 = (EIF_TYPE_INDEX)65535;
	egc_sp_int16 = (EIF_TYPE_INDEX)65535;
	egc_sp_int32 = (EIF_TYPE_INDEX)525;
	egc_sp_int64 = (EIF_TYPE_INDEX)65535;
	egc_sp_real32 = (EIF_TYPE_INDEX)866;
	egc_sp_real64 = (EIF_TYPE_INDEX)611;
	egc_sp_pointer = (EIF_TYPE_INDEX)738;
	egc_sp_ref = (EIF_TYPE_INDEX)416;

	egc_uint8_dtype = 366;
	egc_uint16_dtype = 363;
	egc_uint32_dtype = 360;
	egc_uint64_dtype = 357;
	egc_int8_dtype = 354;
	egc_int16_dtype = 351;
	egc_int32_dtype = 348;
	egc_int64_dtype = 345;
	egc_bool_dtype = 301;
	egc_real32_dtype = 369;
	egc_char_dtype = 298;
	egc_wchar_dtype = 295;
	egc_real64_dtype = 372;
	egc_point_dtype = 304;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 142;
	egc_except_emnger_dtype = 81;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "demo";
	egc_system_location = "/Users/nicologalloperozzi/Desktop/dose2014/implementations/group6/Milan2/src/EIFGENs/demo/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1416940725;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 948;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1544;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 122;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F123_1760;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F123_1761;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 110; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
