
#ifndef _C2_sq64_
#define _C2_sq64_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_POINTER F76_1006(EIF_REFERENCE, EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F76_1007(EIF_REFERENCE, EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_REAL_64 F76_1009(EIF_REFERENCE, EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F76_1010(EIF_REFERENCE, EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_64 F76_1011(EIF_REFERENCE, EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_POINTER F76_1012(EIF_REFERENCE, EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F76_1014(EIF_REFERENCE, EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern void EIF_Minit64(void);

#ifdef __cplusplus
}
#endif

#endif
