/*
 * Generated by ISE 14.05.9.5417 GPL Edition - macosx-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F313_5793();
extern void F315_5950();
extern void F310_5629();
extern void F312_5790();
extern void F430_4779();
extern void F428_5494();
extern void F86_1371();
extern EIF_REFERENCE F86_1358();
extern EIF_BOOLEAN F86_1370();
extern EIF_BOOLEAN F86_1375();
extern void F86_1380();
extern void F86_1381();
extern void F86_1382();
extern void F127_1780();
extern EIF_TYPED_VALUE F127_1781();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F313_5793;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F310_5629;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F430_4779;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F315_5950;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F312_5790;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F428_5494;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F86_1371;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F86_1370;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F86_1358;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F86_1375;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F86_1380;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F86_1381;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F86_1382;

	egc_str_dtype = 314;

	egc_str32_dtype = 311;
	egc_arr_dtype = 429;
	egc_tup_dtype = 293;
	egc_disp_rout_id = 3041;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)595;
	egc_sp_wchar = (EIF_TYPE_INDEX)813;
	egc_sp_bool = (EIF_TYPE_INDEX)666;
	egc_sp_uint8 = (EIF_TYPE_INDEX)769;
	egc_sp_uint16 = (EIF_TYPE_INDEX)884;
	egc_sp_uint32 = (EIF_TYPE_INDEX)731;
	egc_sp_uint64 = (EIF_TYPE_INDEX)510;
	egc_sp_int8 = (EIF_TYPE_INDEX)65535;
	egc_sp_int16 = (EIF_TYPE_INDEX)65535;
	egc_sp_int32 = (EIF_TYPE_INDEX)491;
	egc_sp_int64 = (EIF_TYPE_INDEX)65535;
	egc_sp_real32 = (EIF_TYPE_INDEX)865;
	egc_sp_real64 = (EIF_TYPE_INDEX)578;
	egc_sp_pointer = (EIF_TYPE_INDEX)707;
	egc_sp_ref = (EIF_TYPE_INDEX)418;

	egc_uint8_dtype = 363;
	egc_uint16_dtype = 360;
	egc_uint32_dtype = 357;
	egc_uint64_dtype = 354;
	egc_int8_dtype = 351;
	egc_int16_dtype = 348;
	egc_int32_dtype = 345;
	egc_int64_dtype = 366;
	egc_bool_dtype = 301;
	egc_real32_dtype = 369;
	egc_char_dtype = 298;
	egc_wchar_dtype = 295;
	egc_real64_dtype = 372;
	egc_point_dtype = 304;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 145;
	egc_except_emnger_dtype = 85;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "demo";
	egc_system_location = "/Users/nicologalloperozzi/Desktop/dose2014/implementations/group6/Milan2/src/EIFGENs/demo/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1416235343;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 948;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1564;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 126;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F127_1780;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F127_1781;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 114; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
