/*
 * Generated by ISE 14.05.9.5417 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"
#include "eoffsets.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F737_5723();
extern void F735_5650();
extern void F601_4815();
extern void F728_5531();
extern void F96_1374();
extern EIF_REFERENCE F96_1361();
extern EIF_BOOLEAN F96_1373();
extern EIF_BOOLEAN F96_1378();
extern void F96_1383();
extern void F96_1384();
extern void F96_1385();
extern void egc_routine_tables_init (void);

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;
extern char *(*R2[])();
extern char *(*R6[])();
extern char *(*R3[])();

extern char *(*R4[])();

extern char *(*R5[])();



extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_REFERENCE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F737_5723;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F735_5650;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_INTEGER)) F601_4815;
	egc_str_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_str32_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str32_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_routdisp_fl = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER, EIF_REFERENCE, EIF_BOOLEAN, EIF_INTEGER)) F728_5531;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN, EIF_INTEGER, EIF_INTEGER, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN)) F96_1374;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F96_1373;
	egc_last_exception = (EIF_REFERENCE (*)(EIF_REFERENCE)) F96_1361;
	egc_is_code_ignored = (EIF_BOOLEAN (*)(EIF_REFERENCE, EIF_INTEGER)) F96_1378;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F96_1383;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F96_1384;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F96_1385;

	egc_str_dtype = 740;

	egc_str32_dtype = 739;
	egc_arr_dtype = 600;
	egc_tup_dtype = 684;
	egc_disp_rout_id = 3077;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)803;
	egc_sp_wchar = (EIF_TYPE_INDEX)808;
	egc_sp_bool = (EIF_TYPE_INDEX)801;
	egc_sp_uint8 = (EIF_TYPE_INDEX)807;
	egc_sp_uint16 = (EIF_TYPE_INDEX)809;
	egc_sp_uint32 = (EIF_TYPE_INDEX)806;
	egc_sp_uint64 = (EIF_TYPE_INDEX)800;
	egc_sp_int8 = (EIF_TYPE_INDEX)65535;
	egc_sp_int16 = (EIF_TYPE_INDEX)65535;
	egc_sp_int32 = (EIF_TYPE_INDEX)799;
	egc_sp_int64 = (EIF_TYPE_INDEX)65535;
	egc_sp_real32 = (EIF_TYPE_INDEX)804;
	egc_sp_real64 = (EIF_TYPE_INDEX)802;
	egc_sp_pointer = (EIF_TYPE_INDEX)805;
	egc_sp_ref = (EIF_TYPE_INDEX)798;

	egc_uint8_dtype = 851;
	egc_uint16_dtype = 848;
	egc_uint32_dtype = 845;
	egc_uint64_dtype = 842;
	egc_int8_dtype = 839;
	egc_int16_dtype = 836;
	egc_int32_dtype = 833;
	egc_int64_dtype = 830;
	egc_bool_dtype = 693;
	egc_real32_dtype = 854;
	egc_char_dtype = 690;
	egc_wchar_dtype = 687;
	egc_real64_dtype = 857;
	egc_point_dtype = 726;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 165;
	egc_except_emnger_dtype = 95;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	exception_stack_managed = (EIF_BOOLEAN) 0;
	egc_ecreate = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R2;
	egc_exp_create = (void (**)(EIF_REFERENCE)) R6;
	egc_edispose = (void (**)(void)) R3;
	egc_copy = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R4;
	egc_is_equal = (EIF_BOOLEAN (**)(EIF_REFERENCE, EIF_REFERENCE)) R5;
	egc_ce_rname = egc_ce_rname_init;
	egc_fnbref = egc_fnbref_init;
	egc_fsize = egc_fsize_init;

	egc_system_name = "WBPMS";
	egc_system_location = "D:\\Google Drive\\UNRC\\OPTATIVAS\\D.O.S.E\\dose2014\\implementations\\group6\\src\\EIFGENs\\demo\\F_code";
	egc_compiler_tag = 38;
	egc_project_version = 1418734656;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 949;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make_and_launch";
	egc_rcdt[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_routine_tables_init();
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 134; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
