
#ifndef _C2_wg59_
#define _C2_wg59_

#ifdef __cplusplus
extern "C" {
#endif
RTOSHF (EIF_REFERENCE, 945)


extern EIF_REFERENCE F71_945(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 946)


extern EIF_REFERENCE F71_946(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 947)


extern EIF_REFERENCE F71_947(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 948)


extern EIF_REFERENCE F71_948(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 949)


extern EIF_REFERENCE F71_949(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 950)


extern EIF_REFERENCE F71_950(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 951)


extern EIF_REFERENCE F71_951(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 954)


extern EIF_REFERENCE F71_954(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 955)


extern EIF_REFERENCE F71_955(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 957)


extern EIF_REFERENCE F71_957(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 964)


extern EIF_REFERENCE F71_964(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 966)


extern EIF_REFERENCE F71_966(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 975)


extern EIF_REFERENCE F71_975(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 976)


extern EIF_REFERENCE F71_976(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 979)


extern EIF_REFERENCE F71_979(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 980)


extern EIF_REFERENCE F71_980(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 981)


extern EIF_REFERENCE F71_981(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 984)


extern EIF_REFERENCE F71_984(EIF_REFERENCE);RTOSHF (EIF_REFERENCE, 986)


extern EIF_REFERENCE F71_986(EIF_REFERENCE);
extern void EIF_Minit59(void);

#ifdef __cplusplus
}
#endif

#endif
