
#ifndef _C1_sq9_
#define _C1_sq9_

#ifdef __cplusplus
extern "C" {
#endif

extern EIF_INTEGER_32 F9_93(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32, EIF_POINTER, EIF_INTEGER_32, EIF_POINTER);
extern EIF_INTEGER_32 F9_94(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32, EIF_REAL_64);
extern EIF_INTEGER_32 F9_95(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32, EIF_INTEGER_32);
extern EIF_INTEGER_32 F9_96(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32, EIF_INTEGER_64);
extern EIF_INTEGER_32 F9_97(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F9_99(EIF_REFERENCE, EIF_POINTER, EIF_POINTER);
extern EIF_INTEGER_32 F9_101(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32, EIF_POINTER, EIF_INTEGER_32, EIF_POINTER);
extern EIF_INTEGER_32 F9_102(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F9_103(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER);
extern EIF_INTEGER_32 F9_105(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F9_106(EIF_REFERENCE, EIF_POINTER);
extern EIF_POINTER F9_107(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F9_108(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F9_110(EIF_REFERENCE, EIF_POINTER);
extern EIF_REAL_64 F9_111(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F9_112(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_64 F9_113(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_POINTER F9_114(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_POINTER F9_115(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F9_117(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_POINTER F9_119(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER);
extern EIF_POINTER F9_122(EIF_REFERENCE, EIF_POINTER);
extern EIF_POINTER F9_123(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F9_124(EIF_REFERENCE, EIF_POINTER);
extern EIF_POINTER F9_125(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F9_126(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F9_127(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32);
extern EIF_INTEGER_32 F9_128(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F9_129(EIF_REFERENCE);
extern void F9_130(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_64 F9_131(EIF_REFERENCE, EIF_POINTER);
extern void F9_134(EIF_REFERENCE, EIF_POINTER);
extern void F9_135(EIF_REFERENCE, EIF_POINTER);
extern EIF_POINTER F9_136(EIF_REFERENCE, EIF_POINTER, EIF_POINTER);
extern EIF_INTEGER_32 F9_137(EIF_REFERENCE, EIF_POINTER, EIF_POINTER*, EIF_INTEGER_32, EIF_POINTER);
extern EIF_INTEGER_32 F9_138(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_INTEGER_32, EIF_POINTER*, EIF_POINTER*);
extern void F9_139(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER_32, EIF_POINTER, EIF_POINTER);
extern EIF_INTEGER_32 F9_140(EIF_REFERENCE, EIF_POINTER);
extern EIF_POINTER F9_141(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER);
extern EIF_INTEGER_32 F9_143(EIF_REFERENCE, EIF_POINTER);
extern EIF_INTEGER_32 F9_144(EIF_REFERENCE);
extern EIF_INTEGER_32 F9_145(EIF_REFERENCE, EIF_POINTER);
extern EIF_POINTER F9_146(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER);
extern void EIF_Minit9(void);

#ifdef __cplusplus
}
#endif

#endif
